language: node_js
dist: xenial
sudo: false

matrix:
  include:
    - node_js: 6.14
      env: PUBLISH_TO_NPM=true
    - node_js: 12

before_install:
  - >
    if $(dpkg --compare-versions "${TRAVIS_NODE_VERSION}" "le" "12"); then
      nvm install 12
      nvm use 12
    fi

before_script:
  - nvm use ${TRAVIS_NODE_VERSION}

script:
  - >
    if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
      npm run test:unit:cov
    fi
  - >
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
      npm run test:cov
    fi

deploy:
  provider: npm
  api_key:
    secure: "fpsIqEZNvzcS2g91vwuR8UJo+4Ok6xGuVV/uL5nNia+8cnA+cSfQEmPm4w+0gB3F1UIOGs9ItuMqcBlZOMe7oZxr9Wi+J05LfZGL4cibRXU+ydpnQ0d5Si7/p4W3vskA+SnolDjHPCHAVxZiyRUXswuhMnajbrAejeBvS2n0WF4="
  email: "systems@mollie.com"
  skip_cleanup: true
  on:
    tags: true
    condition: $PUBLISH_TO_NPM = true
